<?
session_start();
include "level2_check.php";

require "header.php";
?>

<link rel="stylesheet" type="text/css" href="takvim/epoch_styles.css" />
<script type="text/javascript" src="takvim/epoch_classes.js"></script>
<script type="text/javascript">
/*You can also place this code in a separate file and link to it like epoch_classes.js*/
	var bas_cal,dp_cal,ms_cal;      
window.onload = function () {
	
	dp_cal  = new Epoch('epoch_popup','popup',document.getElementById('popup_container'));
	dp_cal  = new Epoch('epoch_popup','popup',document.getElementById('popup_container2'));
	ms_cal  = new Epoch('epoch_multi','flat',document.getElementById('multi_container'),true);
};
</script>


<style type="text/css">
<!--
.style1 {color: #999999}
.style2 {font-size: 10px}
.style3 {font-size: 12px}
-->
</style>
<link href="css/all.css" rel="stylesheet" type="text/css">
<style type="text/css">
<!--
.style4 {color: #666666}
.style5 {
	color: #990000;
	font-weight: bold;
}
-->
</style>
<body>






<form name="form1" method="post" action="gecicigir2.php">
<div align="center"><span class="style5">GE&Ccedil;&#304;C&#304; G&Ouml;REV B&#304;LG&#304;S&#304; G&#304;RME B&Ouml;L&Uuml;M&Uuml; </span><br>
</div>
<table border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#EFEFEF">
    <tr bgcolor="#EFEFEF">
      <td bgcolor="#EFEFEF" class="data style3 style4">Ge&ccedil;ici G&ouml;revin Yap&#305;laca&#287;&#305; Ofis </td>
      <td bgcolor="#FFFFE6"><?
		echo "<select name=\"ofis\">";
        echo "<option value=\"\"></option> ";
        include 'includes/ofiscon.php';
         echo "</select> ";

?>
        <br>
      <span class="comment style1 style2"><a href="hatedit.php" target="_blank">Ofis Kodlar&#305;&#305;n&#305; G&ouml;rmek &#304;&ccedil;in T&#305;klay&#305;n </a></span></td>
      <td valign="middle" bgcolor="80B0D8" class="comment style1 style2">&nbsp;</td>
      <td class="data style1 style3"><div align="right" class="style4">Harcirah</div></td>
      <td bgcolor="#FFFFCC"><label>
        <input name="harcirah" type="text" id="harcirah">
      </label></td>
      <td valign="middle" bgcolor="#FFFFCC" class="comment style2 style1"><span class="comment style2">
        <select name=harcirahc id="harcirahc" >
          <option  value="---" selected>Se&ccedil;iniz</option>
          <option  value="ADF" >ADF Andorra (Franc)</option>
          <option  value="ADP">ADP Andorra (Peseta)</option>
          <option  value="AED">AED United Arabic Emir.</option>
          <option  value="AFA">AFA Afghanistan</option>
          <option  value="ALL">ALL Albania</option>
          <option  value="AMD">AMD Armenia</option>
          <option  value="ANG">ANG NL Antilla</option>
          <option  value="AON">AON Angola</option>
          <option  value="ARS">ARS Argentina</option>
          <option  value="ATS">ATS Austria (-> Euro)</option>
          <option  value="AUD">AUD Australia</option>
          <option  value="AWG">AWG Aruba</option>
          <option  value="AZM">AZM Azerbaijan</option>
          <option  value="BBD">BBD Barbados</option>
          <option  value="BDT">BDT Bangladesh</option>
          <option  value="BEF">BEF Belgium (-> Euro)</option>
          <option  value="BGL">BGL Bulgaria</option>
          <option  value="BHD">BHD Bahrain</option>
          <option  value="BIF">BIF Burundi</option>
          <option  value="BMD">BMD Bermuda</option>
          <option  value="BND">BND Brunei</option>
          <option  value="BOB">BOB Bolivia</option>
          <option  value="BRL">BRL Brasil</option>
          <option  value="BSD">BSD Bahamas</option>
          <option  value="BTN">BTN Bhutan</option>
          <option  value="BWP">BWP Botswana</option>
          <option  value="BYR">BYR Belarus</option>
          <option  value="BZD">BZD Belize</option>
          <option  value="CAD">CAD Canada</option>
          <option  value="CDF">CDF Congo/Kinshasa</option>
          <option  value="CHF">CHF Switzerland</option>
          <option  value="CLP">CLP Chile</option>
          <option  value="CNY">CNY China</option>
          <option  value="COP">COP Colombia</option>
          <option  value="CRC">CRC Costa Rica</option>
          <option  value="CUP">CUP Cuba</option>
          <option  value="CVE">CVE Cape Verde</option>
          <option  value="CYP">CYP Cyprus</option>
          <option  value="CZK">CZK Czech Republic</option>
          <option  value="DEM">DEM Germany (-> Euro)</option>
          <option  value="DJF">DJF Djibouti</option>
          <option  value="DKK">DKK Denmark</option>
          <option  value="DOP">DOP Dominican Republic</option>
          <option  value="DZD">DZD Algeria</option>
          <option  value="ECS">ECS Ecuador</option>
          <option  value="EEK">EEK Estonia</option>
          <option  value="EGP">EGP Egypt</option>
          <option  value="ERN">ERN Eritrea</option>
          <option  value="ESP">ESP Spain (-> Euro)</option>
          <option  value="ETB">ETB Ethiopia</option>
          <option  value="EUR">EUR Euroland</option>
          <option  value="FIM">FIM Finland (-> Euro)</option>
          <option  value="FJD">FJD Fiji</option>
          <option  value="FKP">FKP Falkland Islands</option>
          <option  value="FRF">FRF France (-> Euro)</option>
          <option  value="GBP">GBP Great-Britain</option>
          <option  value="GEL">GEL Georgia</option>
          <option  value="GHC">GHC Ghana</option>
          <option  value="GIP">GIP Gibraltar</option>
          <option  value="GMD">GMD Gambia</option>
          <option  value="GNF">GNF Guinea</option>
          <option  value="GRD">GRD Greece (-> Euro)</option>
          <option  value="GTQ">GTQ Guatemala</option>
          <option  value="GYD">GYD Guyana</option>
          <option  value="HKD">HKD Hong-Kong</option>
          <option  value="HNL">HNL Honduras</option>
          <option  value="HRK">HRK Croatia</option>
          <option  value="HTG">HTG Haiti</option>
          <option  value="HUF">HUF Hungary</option>
          <option  value="IDR">IDR Indonesia</option>
          <option  value="IEP">IEP Ireland (-> Euro)</option>
          <option  value="ILS">ILS Israel</option>
          <option  value="IMP">IMP Isle of Man</option>
          <option  value="INR">INR India</option>
          <option  value="IQD">IQD Iraq</option>
          <option  value="IRR">IRR Iran</option>
          <option  value="ISK">ISK Iceland</option>
          <option  value="ITL">ITL Italy (-> Euro)</option>
          <option  value="JEP">JEP Jersey</option>
          <option  value="JMD">JMD Jamaica</option>
          <option value="JOD">JOD Jordania</option>
          <option  value="JPY">JPY Japan</option>
          <option  value="KES">KES Kenya</option>
          <option  value="KGS">KGS Kyrgyzstan</option>
          <option  value="KHR">KHR Cambodia</option>
          <option  value="KMF">KMF Comoros</option>
          <option  value="KPW">KPW North Korea</option>
          <option  value="KRW">KRW South Korea</option>
          <option  value="KWD">KWD Kuwait</option>
          <option  value="KYD">KYD Cayman Islands</option>
          <option  value="KZT">KZT Kazakhstan</option>
          <option  value="LAK">LAK Laos</option>
          <option  value="LBP">LBP Lebanon</option>
          <option  value="LKR">LKR Sri Lanka</option>
          <option  value="LRD">LRD Liberia</option>
          <option  value="LSL">LSL Lesotho</option>
          <option  value="LTL">LTL Lithuania</option>
          <option  value="LUF">LUF Luxembourg (-> Euro)</option>
          <option  value="LVL">LVL Latvia</option>
          <option  value="LYD">LYD Libya</option>
          <option  value="MAD">MAD Morocco</option>
          <option  value="MDL">MDL Moldova</option>
          <option  value="MGF">MGF Madagascar</option>
          <option  value="MKD">MKD Macedonia</option>
          <option  value="MMK">MMK Myanmar</option>
          <option  value="MNT">MNT Mongolia</option>
          <option  value="MOP">MOP Macau</option>
          <option  value="MRO">MRO Mauritania</option>
          <option  value="MTL">MTL Malta</option>
          <option  value="MUR">MUR Mauritius Island</option>
          <option  value="MVR">MVR Maldives</option>
          <option  value="MWK">MWK Malawi</option>
          <option  value="MXN">MXN Mexico</option>
          <option  value="MYR">MYR Malaysia</option>
          <option  value="MZM">MZM Mozambique</option>
          <option  value="NAD">NAD Namibia</option>
          <option  value="NGN">NGN Nigeria</option>
          <option  value="NIO">NIO Nicaragua</option>
          <option  value="NLG">NLG Holland (-> Euro)</option>
          <option  value="NOK">NOK Norway</option>
          <option  value="NPR">NPR Nepal</option>
          <option  value="NTD">NTD Taiwan</option>
          <option  value="NZD">NZD New-Zealand</option>
          <option  value="OMR">OMR Oman</option>
          <option  value="PAB">PAB Panama</option>
          <option  value="PEN">PEN Peru</option>
          <option  value="PGK">PGK Papua New Guinea</option>
          <option  value="PHP">PHP Philippines</option>
          <option  value="PKR">PKR Pakistan</option>
          <option  value="PLN">PLN Poland</option>
          <option  value="PSL">PSL Seborga</option>
          <option  value="PTE">PTE Portugal (-> Euro)</option>
          <option  value="PYG">PYG Paraguay</option>
          <option  value="QAR">QAR Qatar</option>
          <option  value="ROL">ROL Romania</option>
          <option  value="RUB">RUB Russia</option>
          <option  value="RWF">RWF Rwanda</option>
          <option  value="SAR">SAR Saudi Arabia</option>
          <option  value="SBD">SBD Solomon Islands</option>
          <option  value="SCR">SCR Seychelles</option>
          <option  value="SDD">SDD Sudan (Dinar)</option>
          <option  value="SDP">SDP Sudan (Pound)</option>
          <option  value="SEK">SEK Sweden</option>
          <option  value="SGD">SGD Singapore</option>
          <option  value="SHP">SHP Saint Helena</option>
          <option  value="SIT">SIT Slovenia</option>
          <option  value="SKK">SKK Slovakia</option>
          <option  value="SLL">SLL Sierra Leone</option>
          <option  value="SOS">SOS Somalia</option>
          <option  value="SRG">SRG Suriname</option>
          <option  value="STD">STD Saint Tome/Principe</option>
          <option  value="SVC">SVC El Salvador</option>
          <option  value="SYP">SYP Syria</option>
          <option  value="SZL">SZL Swaziland</option>
          <option  value="THB">THB Thailand</option>
          <option  value="TJS">TJS Tajikistan</option>
          <option  value="TMM">TMM Turkmenistan</option>
          <option  value="TND">TND Tunisia</option>
          <option  value="TOP">TOP Tonga</option>
          <option  value="TRL">TRL Turkey (-2004)</option>
          <option  value="TRY">TRY Turkey (2005-)</option>
          <option  value="TTD">TTD Trinidad & Tobago</option>
          <option  value="TVD">TVD Tuvalu</option>
          <option  value="TWD">TWD Taiwan (NTD)</option>
          <option  value="TZS">TZS Tanzania</option>
          <option  value="UAH">UAH Ukraine</option>
          <option  value="UGX">UGX Uganda</option>
          <option  value="USD">USD United States</option>
          <option  value="UYP">UYP Uruguay</option>
          <option  value="UZS">UZS Uzbekistan</option>
          <option  value="VEB">VEB Venezuela</option>
          <option  value="VND">VND Vietnam</option>
          <option  value="VUV">VUV Vanuatu</option>
          <option  value="WST">WST Samoa (Western)</option>
          <option  value="XAF">XAF CFA Franc BEAC</option>
          <option  value="XAG">XAG Silver gram</option>
          <option  value="XAU">XAU Gold gram</option>
          <option  value="XCD">XCD East Caribbean</option>
          <option  value="XDR">XDR Special Drawing Right</option>
          <option  value="XEU">XEU ECU-European Curr. Unit</option>
          <option  value="XOF">XOF CFA Franc BCEAO</option>
          <option  value="XPD">XPD Palladium gram</option>
          <option  value="XPF">XPF French Pacific</option>
          <option  value="XPT">XPT Platinium gram</option>
          <option  value="YER">YER Yemen</option>
          <option  value="YUN">YUN Yugoslavia</option>
          <option  value="ZAR">ZAR South Africa</option>
          <option  value="ZMK">ZMK Zambia</option>
          <option  value="ZWD">ZWD Zimbabwe</option>
        </select>
      </span></td>
    </tr>
    <tr bgcolor="#EFEFEF">
      <td bgcolor="#EFEFEF" class="data style3 style4">Ge&ccedil;ici G&ouml;revin Yap&#305;laca&#287;&#305; Ba&#351;kanl&#305;k </td>
      <td bgcolor="#FFFFE6"><label>
        <select name="baskan" id="baskan">
          <option value="--" selected>Se&ccedil;iniz</option>
          <option value="Pazarlama Sat&#305;&#351; B&#351;k ">Pazarlama Sat&#305;&#351; B&#351;k </option>
          <option value="&#304;dari &#304;&#351;ler Md">&#304;dari &#304;&#351;ler Md</option>
          <option value="&Uuml;retim Planlama B&#351;k">&Uuml;retim Planlama B&#351;k</option>
          <option value="Gelir Y&ouml;netim B&#351;k">Gelir Y&ouml;netim B&#351;k</option>
          <option value="Kargo B&#351;k">Kargo B&#351;k</option>
          <option value="&#304;&#351; Geli&#351;tirme B&#351;k">&#304;&#351; Geli&#351;tirme B&#351;k</option>
        </select>
      </label></td>
      <td bgcolor="80B0D8">&nbsp;</td>
      <td class="data style1 style3"><div align="right" class="style4">Yolluk</div></td>
      <td bgcolor="#FFFFCC"><input name="yolluk" type="text" id="yolluk"></td>
      <td valign="middle" bgcolor="#FFFFCC" class="comment style2 style1"><span class="comment style2">
        <select name=yollukc id="yollukc" >
          <option  value="---" selected>Se&ccedil;iniz</option>
          <option  value="ADF" >ADF Andorra (Franc)</option>
          <option  value="ADP">ADP Andorra (Peseta)</option>
          <option  value="AED">AED United Arabic Emir.</option>
          <option  value="AFA">AFA Afghanistan</option>
          <option  value="ALL">ALL Albania</option>
          <option  value="AMD">AMD Armenia</option>
          <option  value="ANG">ANG NL Antilla</option>
          <option  value="AON">AON Angola</option>
          <option  value="ARS">ARS Argentina</option>
          <option  value="ATS">ATS Austria (-> Euro)</option>
          <option  value="AUD">AUD Australia</option>
          <option  value="AWG">AWG Aruba</option>
          <option  value="AZM">AZM Azerbaijan</option>
          <option  value="BBD">BBD Barbados</option>
          <option  value="BDT">BDT Bangladesh</option>
          <option  value="BEF">BEF Belgium (-> Euro)</option>
          <option  value="BGL">BGL Bulgaria</option>
          <option  value="BHD">BHD Bahrain</option>
          <option  value="BIF">BIF Burundi</option>
          <option  value="BMD">BMD Bermuda</option>
          <option  value="BND">BND Brunei</option>
          <option  value="BOB">BOB Bolivia</option>
          <option  value="BRL">BRL Brasil</option>
          <option  value="BSD">BSD Bahamas</option>
          <option  value="BTN">BTN Bhutan</option>
          <option  value="BWP">BWP Botswana</option>
          <option  value="BYR">BYR Belarus</option>
          <option  value="BZD">BZD Belize</option>
          <option  value="CAD">CAD Canada</option>
          <option  value="CDF">CDF Congo/Kinshasa</option>
          <option  value="CHF">CHF Switzerland</option>
          <option  value="CLP">CLP Chile</option>
          <option  value="CNY">CNY China</option>
          <option  value="COP">COP Colombia</option>
          <option  value="CRC">CRC Costa Rica</option>
          <option  value="CUP">CUP Cuba</option>
          <option  value="CVE">CVE Cape Verde</option>
          <option  value="CYP">CYP Cyprus</option>
          <option  value="CZK">CZK Czech Republic</option>
          <option  value="DEM">DEM Germany (-> Euro)</option>
          <option  value="DJF">DJF Djibouti</option>
          <option  value="DKK">DKK Denmark</option>
          <option  value="DOP">DOP Dominican Republic</option>
          <option  value="DZD">DZD Algeria</option>
          <option  value="ECS">ECS Ecuador</option>
          <option  value="EEK">EEK Estonia</option>
          <option  value="EGP">EGP Egypt</option>
          <option  value="ERN">ERN Eritrea</option>
          <option  value="ESP">ESP Spain (-> Euro)</option>
          <option  value="ETB">ETB Ethiopia</option>
          <option  value="EUR">EUR Euroland</option>
          <option  value="FIM">FIM Finland (-> Euro)</option>
          <option  value="FJD">FJD Fiji</option>
          <option  value="FKP">FKP Falkland Islands</option>
          <option  value="FRF">FRF France (-> Euro)</option>
          <option  value="GBP">GBP Great-Britain</option>
          <option  value="GEL">GEL Georgia</option>
          <option  value="GHC">GHC Ghana</option>
          <option  value="GIP">GIP Gibraltar</option>
          <option  value="GMD">GMD Gambia</option>
          <option  value="GNF">GNF Guinea</option>
          <option  value="GRD">GRD Greece (-> Euro)</option>
          <option  value="GTQ">GTQ Guatemala</option>
          <option  value="GYD">GYD Guyana</option>
          <option  value="HKD">HKD Hong-Kong</option>
          <option  value="HNL">HNL Honduras</option>
          <option  value="HRK">HRK Croatia</option>
          <option  value="HTG">HTG Haiti</option>
          <option  value="HUF">HUF Hungary</option>
          <option  value="IDR">IDR Indonesia</option>
          <option  value="IEP">IEP Ireland (-> Euro)</option>
          <option  value="ILS">ILS Israel</option>
          <option  value="IMP">IMP Isle of Man</option>
          <option  value="INR">INR India</option>
          <option  value="IQD">IQD Iraq</option>
          <option  value="IRR">IRR Iran</option>
          <option  value="ISK">ISK Iceland</option>
          <option  value="ITL">ITL Italy (-> Euro)</option>
          <option  value="JEP">JEP Jersey</option>
          <option  value="JMD">JMD Jamaica</option>
          <option value="JOD">JOD Jordania</option>
          <option  value="JPY">JPY Japan</option>
          <option  value="KES">KES Kenya</option>
          <option  value="KGS">KGS Kyrgyzstan</option>
          <option  value="KHR">KHR Cambodia</option>
          <option  value="KMF">KMF Comoros</option>
          <option  value="KPW">KPW North Korea</option>
          <option  value="KRW">KRW South Korea</option>
          <option  value="KWD">KWD Kuwait</option>
          <option  value="KYD">KYD Cayman Islands</option>
          <option  value="KZT">KZT Kazakhstan</option>
          <option  value="LAK">LAK Laos</option>
          <option  value="LBP">LBP Lebanon</option>
          <option  value="LKR">LKR Sri Lanka</option>
          <option  value="LRD">LRD Liberia</option>
          <option  value="LSL">LSL Lesotho</option>
          <option  value="LTL">LTL Lithuania</option>
          <option  value="LUF">LUF Luxembourg (-> Euro)</option>
          <option  value="LVL">LVL Latvia</option>
          <option  value="LYD">LYD Libya</option>
          <option  value="MAD">MAD Morocco</option>
          <option  value="MDL">MDL Moldova</option>
          <option  value="MGF">MGF Madagascar</option>
          <option  value="MKD">MKD Macedonia</option>
          <option  value="MMK">MMK Myanmar</option>
          <option  value="MNT">MNT Mongolia</option>
          <option  value="MOP">MOP Macau</option>
          <option  value="MRO">MRO Mauritania</option>
          <option  value="MTL">MTL Malta</option>
          <option  value="MUR">MUR Mauritius Island</option>
          <option  value="MVR">MVR Maldives</option>
          <option  value="MWK">MWK Malawi</option>
          <option  value="MXN">MXN Mexico</option>
          <option  value="MYR">MYR Malaysia</option>
          <option  value="MZM">MZM Mozambique</option>
          <option  value="NAD">NAD Namibia</option>
          <option  value="NGN">NGN Nigeria</option>
          <option  value="NIO">NIO Nicaragua</option>
          <option  value="NLG">NLG Holland (-> Euro)</option>
          <option  value="NOK">NOK Norway</option>
          <option  value="NPR">NPR Nepal</option>
          <option  value="NTD">NTD Taiwan</option>
          <option  value="NZD">NZD New-Zealand</option>
          <option  value="OMR">OMR Oman</option>
          <option  value="PAB">PAB Panama</option>
          <option  value="PEN">PEN Peru</option>
          <option  value="PGK">PGK Papua New Guinea</option>
          <option  value="PHP">PHP Philippines</option>
          <option  value="PKR">PKR Pakistan</option>
          <option  value="PLN">PLN Poland</option>
          <option  value="PSL">PSL Seborga</option>
          <option  value="PTE">PTE Portugal (-> Euro)</option>
          <option  value="PYG">PYG Paraguay</option>
          <option  value="QAR">QAR Qatar</option>
          <option  value="ROL">ROL Romania</option>
          <option  value="RUB">RUB Russia</option>
          <option  value="RWF">RWF Rwanda</option>
          <option  value="SAR">SAR Saudi Arabia</option>
          <option  value="SBD">SBD Solomon Islands</option>
          <option  value="SCR">SCR Seychelles</option>
          <option  value="SDD">SDD Sudan (Dinar)</option>
          <option  value="SDP">SDP Sudan (Pound)</option>
          <option  value="SEK">SEK Sweden</option>
          <option  value="SGD">SGD Singapore</option>
          <option  value="SHP">SHP Saint Helena</option>
          <option  value="SIT">SIT Slovenia</option>
          <option  value="SKK">SKK Slovakia</option>
          <option  value="SLL">SLL Sierra Leone</option>
          <option  value="SOS">SOS Somalia</option>
          <option  value="SRG">SRG Suriname</option>
          <option  value="STD">STD Saint Tome/Principe</option>
          <option  value="SVC">SVC El Salvador</option>
          <option  value="SYP">SYP Syria</option>
          <option  value="SZL">SZL Swaziland</option>
          <option  value="THB">THB Thailand</option>
          <option  value="TJS">TJS Tajikistan</option>
          <option  value="TMM">TMM Turkmenistan</option>
          <option  value="TND">TND Tunisia</option>
          <option  value="TOP">TOP Tonga</option>
          <option  value="TRL">TRL Turkey (-2004)</option>
          <option  value="TRY">TRY Turkey (2005-)</option>
          <option  value="TTD">TTD Trinidad & Tobago</option>
          <option  value="TVD">TVD Tuvalu</option>
          <option  value="TWD">TWD Taiwan (NTD)</option>
          <option  value="TZS">TZS Tanzania</option>
          <option  value="UAH">UAH Ukraine</option>
          <option  value="UGX">UGX Uganda</option>
          <option  value="USD">USD United States</option>
          <option  value="UYP">UYP Uruguay</option>
          <option  value="UZS">UZS Uzbekistan</option>
          <option  value="VEB">VEB Venezuela</option>
          <option  value="VND">VND Vietnam</option>
          <option  value="VUV">VUV Vanuatu</option>
          <option  value="WST">WST Samoa (Western)</option>
          <option  value="XAF">XAF CFA Franc BEAC</option>
          <option  value="XAG">XAG Silver gram</option>
          <option  value="XAU">XAU Gold gram</option>
          <option  value="XCD">XCD East Caribbean</option>
          <option  value="XDR">XDR Special Drawing Right</option>
          <option  value="XEU">XEU ECU-European Curr. Unit</option>
          <option  value="XOF">XOF CFA Franc BCEAO</option>
          <option  value="XPD">XPD Palladium gram</option>
          <option  value="XPF">XPF French Pacific</option>
          <option  value="XPT">XPT Platinium gram</option>
          <option  value="YER">YER Yemen</option>
          <option  value="YUN">YUN Yugoslavia</option>
          <option  value="ZAR">ZAR South Africa</option>
          <option  value="ZMK">ZMK Zambia</option>
          <option  value="ZWD">ZWD Zimbabwe</option>
        </select>
      </span></td>
    </tr>
    <tr bgcolor="#EFEFEF">
      <td bgcolor="#EFEFEF" class="data style3 style4">Ge&ccedil;ici G&ouml;revin Yap&#305;laca&#287;&#305; M&uuml;d&uuml;rl&uuml;k </td>
      <td bgcolor="#FFFFE6"><label>
        <select name="bolge" id="bolge">
          <option value="--" selected>Se&ccedil;iniz </option>
          <option value="Bat&#305; Avrupa ve Afrika">Bat&#305; Avrupa ve Afrika</option>
          <option value="G&uuml;ney Avrupa ve Balkanlar">G&uuml;ney Avrupa ve Balkanlar</option>
          <option value="Amerika ve Uzak Do&#287;u ">Amerika ve Uzak Do&#287;u </option>
          <option value="Anadolu ">Anadolu </option>
          <option value="Marmara-Ege-Akdeniz">Marmara-Ege-Akdeniz</option>
          <option value="Kuzey Avrupa ve T&uuml;rki Cumhuriyetler">Kuzey Avrupa ve T&uuml;rki Cumhuriyetler</option>
          <option value="Orta Avrupa">Orta Avrupa</option>
          <option value="Orta Do&#287;u ve K&#305;br&#305;s">Orta Do&#287;u ve K&#305;br&#305;s</option>
          <option value="Network Planlama">Network Planlama</option>
          <option value="Tarife">Tarife</option>
          <option value="Charter">Charter</option>
          <option value="Slot Koordinasyon">Slot Koordinasyon</option>
          <option value="Gelir Y&ouml;n ve &Uuml;cret">Gelir Y&ouml;n ve &Uuml;cret</option>
          <option value="Rezervasyon Kontrol">Rezervasyon Kontrol</option>
          <option value="Rezervasyon Sistem">Rezervasyon Sistem</option>
          <option value="Genel Da&#287;&#305;t&#305;m Sistem">Genel Da&#287;&#305;t&#305;m Sistem</option>
          <option value="Uluslararas&#305; &#304;li&#351;kiler">Uluslararas&#305; &#304;li&#351;kiler</option>
          <option value="Acenteler">Acenteler</option>
          <option value="Destek">Destek</option>
          <option value="Sat&#305;&#351; Art&#305;rma">Sat&#305;&#351; Art&#305;rma</option>
          <option value="Kargo Rezervasyon">Kargo Rezervasyon</option>
          <option value="Kargo Sat&#305;&#351;">Kargo Sat&#305;&#351;</option>
          <option value="Kargo Planlama ve Charter">Kargo Planlama ve Charter</option>
          <option value="Kargo Handling S&ouml;zle&#351;meleri">Kargo Handling S&ouml;zle&#351;meleri</option>
          <option value="Kargo Operasyon Kontrol">Kargo Operasyon Kontrol</option>
          <option value="&#304;stanbul Kargo">&#304;stanbul Kargo</option>
          <option value="Ankara Kargo">Ankara Kargo</option>
          <option value="&#304;zmir Kargo">&#304;zmir Kargo</option>
          <option value="Adana Kargo">Adana Kargo</option>
          <option value="Rezervasyon ve Telefonla Sat&#305;&#351;">Rezervasyon ve Telefonla Sat&#305;&#351;</option>
          <option value="&Uuml;r&uuml;n Geli&#351;tirme">&Uuml;r&uuml;n Geli&#351;tirme</option>
          <option value="E-Ticaret">E-Ticaret</option>
          <option value="M&uuml;&#351;teri &#304;li&#351;kileri">M&uuml;&#351;teri &#304;li&#351;kileri</option>
          <option value="Antalya Kargo">Antalya Kargo</option>
          <option value="Kargo Sistem Mdr">Kargo Sistem Mdr</option>
		  <option value="IATA Biletleme ve Kurallar">IATA Biletleme ve Kurallar</option>
        </select>
      </label></td>
      <td bgcolor="80B0D8">&nbsp;</td>
      <td class="data style1 style3"><div align="right" class="style4">Otel Masraf&#305; </div></td>
      <td bgcolor="#FFFFCC"><input name="otel" type="text" id="otel"></td>
      <td valign="middle" bgcolor="#FFFFCC" class="comment style2 style1"><span class="comment style2">
        <select name=otelc id="otelc" >
          <option  value="---" selected>Se&ccedil;iniz</option>
          <option  value="ADF" >ADF Andorra (Franc)</option>
          <option  value="ADP">ADP Andorra (Peseta)</option>
          <option  value="AED">AED United Arabic Emir.</option>
          <option  value="AFA">AFA Afghanistan</option>
          <option  value="ALL">ALL Albania</option>
          <option  value="AMD">AMD Armenia</option>
          <option  value="ANG">ANG NL Antilla</option>
          <option  value="AON">AON Angola</option>
          <option  value="ARS">ARS Argentina</option>
          <option  value="ATS">ATS Austria (-> Euro)</option>
          <option  value="AUD">AUD Australia</option>
          <option  value="AWG">AWG Aruba</option>
          <option  value="AZM">AZM Azerbaijan</option>
          <option  value="BBD">BBD Barbados</option>
          <option  value="BDT">BDT Bangladesh</option>
          <option  value="BEF">BEF Belgium (-> Euro)</option>
          <option  value="BGL">BGL Bulgaria</option>
          <option  value="BHD">BHD Bahrain</option>
          <option  value="BIF">BIF Burundi</option>
          <option  value="BMD">BMD Bermuda</option>
          <option  value="BND">BND Brunei</option>
          <option  value="BOB">BOB Bolivia</option>
          <option  value="BRL">BRL Brasil</option>
          <option  value="BSD">BSD Bahamas</option>
          <option  value="BTN">BTN Bhutan</option>
          <option  value="BWP">BWP Botswana</option>
          <option  value="BYR">BYR Belarus</option>
          <option  value="BZD">BZD Belize</option>
          <option  value="CAD">CAD Canada</option>
          <option  value="CDF">CDF Congo/Kinshasa</option>
          <option  value="CHF">CHF Switzerland</option>
          <option  value="CLP">CLP Chile</option>
          <option  value="CNY">CNY China</option>
          <option  value="COP">COP Colombia</option>
          <option  value="CRC">CRC Costa Rica</option>
          <option  value="CUP">CUP Cuba</option>
          <option  value="CVE">CVE Cape Verde</option>
          <option  value="CYP">CYP Cyprus</option>
          <option  value="CZK">CZK Czech Republic</option>
          <option  value="DEM">DEM Germany (-> Euro)</option>
          <option  value="DJF">DJF Djibouti</option>
          <option  value="DKK">DKK Denmark</option>
          <option  value="DOP">DOP Dominican Republic</option>
          <option  value="DZD">DZD Algeria</option>
          <option  value="ECS">ECS Ecuador</option>
          <option  value="EEK">EEK Estonia</option>
          <option  value="EGP">EGP Egypt</option>
          <option  value="ERN">ERN Eritrea</option>
          <option  value="ESP">ESP Spain (-> Euro)</option>
          <option  value="ETB">ETB Ethiopia</option>
          <option  value="EUR">EUR Euroland</option>
          <option  value="FIM">FIM Finland (-> Euro)</option>
          <option  value="FJD">FJD Fiji</option>
          <option  value="FKP">FKP Falkland Islands</option>
          <option  value="FRF">FRF France (-> Euro)</option>
          <option  value="GBP">GBP Great-Britain</option>
          <option  value="GEL">GEL Georgia</option>
          <option  value="GHC">GHC Ghana</option>
          <option  value="GIP">GIP Gibraltar</option>
          <option  value="GMD">GMD Gambia</option>
          <option  value="GNF">GNF Guinea</option>
          <option  value="GRD">GRD Greece (-> Euro)</option>
          <option  value="GTQ">GTQ Guatemala</option>
          <option  value="GYD">GYD Guyana</option>
          <option  value="HKD">HKD Hong-Kong</option>
          <option  value="HNL">HNL Honduras</option>
          <option  value="HRK">HRK Croatia</option>
          <option  value="HTG">HTG Haiti</option>
          <option  value="HUF">HUF Hungary</option>
          <option  value="IDR">IDR Indonesia</option>
          <option  value="IEP">IEP Ireland (-> Euro)</option>
          <option  value="ILS">ILS Israel</option>
          <option  value="IMP">IMP Isle of Man</option>
          <option  value="INR">INR India</option>
          <option  value="IQD">IQD Iraq</option>
          <option  value="IRR">IRR Iran</option>
          <option  value="ISK">ISK Iceland</option>
          <option  value="ITL">ITL Italy (-> Euro)</option>
          <option  value="JEP">JEP Jersey</option>
          <option  value="JMD">JMD Jamaica</option>
          <option value="JOD">JOD Jordania</option>
          <option  value="JPY">JPY Japan</option>
          <option  value="KES">KES Kenya</option>
          <option  value="KGS">KGS Kyrgyzstan</option>
          <option  value="KHR">KHR Cambodia</option>
          <option  value="KMF">KMF Comoros</option>
          <option  value="KPW">KPW North Korea</option>
          <option  value="KRW">KRW South Korea</option>
          <option  value="KWD">KWD Kuwait</option>
          <option  value="KYD">KYD Cayman Islands</option>
          <option  value="KZT">KZT Kazakhstan</option>
          <option  value="LAK">LAK Laos</option>
          <option  value="LBP">LBP Lebanon</option>
          <option  value="LKR">LKR Sri Lanka</option>
          <option  value="LRD">LRD Liberia</option>
          <option  value="LSL">LSL Lesotho</option>
          <option  value="LTL">LTL Lithuania</option>
          <option  value="LUF">LUF Luxembourg (-> Euro)</option>
          <option  value="LVL">LVL Latvia</option>
          <option  value="LYD">LYD Libya</option>
          <option  value="MAD">MAD Morocco</option>
          <option  value="MDL">MDL Moldova</option>
          <option  value="MGF">MGF Madagascar</option>
          <option  value="MKD">MKD Macedonia</option>
          <option  value="MMK">MMK Myanmar</option>
          <option  value="MNT">MNT Mongolia</option>
          <option  value="MOP">MOP Macau</option>
          <option  value="MRO">MRO Mauritania</option>
          <option  value="MTL">MTL Malta</option>
          <option  value="MUR">MUR Mauritius Island</option>
          <option  value="MVR">MVR Maldives</option>
          <option  value="MWK">MWK Malawi</option>
          <option  value="MXN">MXN Mexico</option>
          <option  value="MYR">MYR Malaysia</option>
          <option  value="MZM">MZM Mozambique</option>
          <option  value="NAD">NAD Namibia</option>
          <option  value="NGN">NGN Nigeria</option>
          <option  value="NIO">NIO Nicaragua</option>
          <option  value="NLG">NLG Holland (-> Euro)</option>
          <option  value="NOK">NOK Norway</option>
          <option  value="NPR">NPR Nepal</option>
          <option  value="NTD">NTD Taiwan</option>
          <option  value="NZD">NZD New-Zealand</option>
          <option  value="OMR">OMR Oman</option>
          <option  value="PAB">PAB Panama</option>
          <option  value="PEN">PEN Peru</option>
          <option  value="PGK">PGK Papua New Guinea</option>
          <option  value="PHP">PHP Philippines</option>
          <option  value="PKR">PKR Pakistan</option>
          <option  value="PLN">PLN Poland</option>
          <option  value="PSL">PSL Seborga</option>
          <option  value="PTE">PTE Portugal (-> Euro)</option>
          <option  value="PYG">PYG Paraguay</option>
          <option  value="QAR">QAR Qatar</option>
          <option  value="ROL">ROL Romania</option>
          <option  value="RUB">RUB Russia</option>
          <option  value="RWF">RWF Rwanda</option>
          <option  value="SAR">SAR Saudi Arabia</option>
          <option  value="SBD">SBD Solomon Islands</option>
          <option  value="SCR">SCR Seychelles</option>
          <option  value="SDD">SDD Sudan (Dinar)</option>
          <option  value="SDP">SDP Sudan (Pound)</option>
          <option  value="SEK">SEK Sweden</option>
          <option  value="SGD">SGD Singapore</option>
          <option  value="SHP">SHP Saint Helena</option>
          <option  value="SIT">SIT Slovenia</option>
          <option  value="SKK">SKK Slovakia</option>
          <option  value="SLL">SLL Sierra Leone</option>
          <option  value="SOS">SOS Somalia</option>
          <option  value="SRG">SRG Suriname</option>
          <option  value="STD">STD Saint Tome/Principe</option>
          <option  value="SVC">SVC El Salvador</option>
          <option  value="SYP">SYP Syria</option>
          <option  value="SZL">SZL Swaziland</option>
          <option  value="THB">THB Thailand</option>
          <option  value="TJS">TJS Tajikistan</option>
          <option  value="TMM">TMM Turkmenistan</option>
          <option  value="TND">TND Tunisia</option>
          <option  value="TOP">TOP Tonga</option>
          <option  value="TRL">TRL Turkey (-2004)</option>
          <option  value="TRY">TRY Turkey (2005-)</option>
          <option  value="TTD">TTD Trinidad & Tobago</option>
          <option  value="TVD">TVD Tuvalu</option>
          <option  value="TWD">TWD Taiwan (NTD)</option>
          <option  value="TZS">TZS Tanzania</option>
          <option  value="UAH">UAH Ukraine</option>
          <option  value="UGX">UGX Uganda</option>
          <option  value="USD">USD United States</option>
          <option  value="UYP">UYP Uruguay</option>
          <option  value="UZS">UZS Uzbekistan</option>
          <option  value="VEB">VEB Venezuela</option>
          <option  value="VND">VND Vietnam</option>
          <option  value="VUV">VUV Vanuatu</option>
          <option  value="WST">WST Samoa (Western)</option>
          <option  value="XAF">XAF CFA Franc BEAC</option>
          <option  value="XAG">XAG Silver gram</option>
          <option  value="XAU">XAU Gold gram</option>
          <option  value="XCD">XCD East Caribbean</option>
          <option  value="XDR">XDR Special Drawing Right</option>
          <option  value="XEU">XEU ECU-European Curr. Unit</option>
          <option  value="XOF">XOF CFA Franc BCEAO</option>
          <option  value="XPD">XPD Palladium gram</option>
          <option  value="XPF">XPF French Pacific</option>
          <option  value="XPT">XPT Platinium gram</option>
          <option  value="YER">YER Yemen</option>
          <option  value="YUN">YUN Yugoslavia</option>
          <option  value="ZAR">ZAR South Africa</option>
          <option  value="ZMK">ZMK Zambia</option>
          <option  value="ZWD">ZWD Zimbabwe</option>
        </select>
      </span></td>
    </tr>
    <tr bgcolor="#EFEFEF">
      <td bgcolor="#EFEFEF" class="data style3 style4">Sicil No </td>
      <td bgcolor="#FFFFE6"><input name="sicil" type="text" id="sicil"></td>
      <td valign="middle" bgcolor="80B0D8" class="comment style2 style1">&nbsp;</td>
      <td class="data style1 style3"><div align="right" class="style4">Pasaport Harcamalar&#305; </div></td>
      <td bgcolor="#FFFFCC"><input name="pasaport" type="text" id="pasaport"></td>
      <td valign="middle" bgcolor="#FFFFCC" class="comment style2 style1"><span class="comment style2">
        <select name=pasaportc id="pasaportc" >
          <option  value="---" selected>Se&ccedil;iniz</option>
          <option  value="ADF" >ADF Andorra (Franc)</option>
          <option  value="ADP">ADP Andorra (Peseta)</option>
          <option  value="AED">AED United Arabic Emir.</option>
          <option  value="AFA">AFA Afghanistan</option>
          <option  value="ALL">ALL Albania</option>
          <option  value="AMD">AMD Armenia</option>
          <option  value="ANG">ANG NL Antilla</option>
          <option  value="AON">AON Angola</option>
          <option  value="ARS">ARS Argentina</option>
          <option  value="ATS">ATS Austria (-> Euro)</option>
          <option  value="AUD">AUD Australia</option>
          <option  value="AWG">AWG Aruba</option>
          <option  value="AZM">AZM Azerbaijan</option>
          <option  value="BBD">BBD Barbados</option>
          <option  value="BDT">BDT Bangladesh</option>
          <option  value="BEF">BEF Belgium (-> Euro)</option>
          <option  value="BGL">BGL Bulgaria</option>
          <option  value="BHD">BHD Bahrain</option>
          <option  value="BIF">BIF Burundi</option>
          <option  value="BMD">BMD Bermuda</option>
          <option  value="BND">BND Brunei</option>
          <option  value="BOB">BOB Bolivia</option>
          <option  value="BRL">BRL Brasil</option>
          <option  value="BSD">BSD Bahamas</option>
          <option  value="BTN">BTN Bhutan</option>
          <option  value="BWP">BWP Botswana</option>
          <option  value="BYR">BYR Belarus</option>
          <option  value="BZD">BZD Belize</option>
          <option  value="CAD">CAD Canada</option>
          <option  value="CDF">CDF Congo/Kinshasa</option>
          <option  value="CHF">CHF Switzerland</option>
          <option  value="CLP">CLP Chile</option>
          <option  value="CNY">CNY China</option>
          <option  value="COP">COP Colombia</option>
          <option  value="CRC">CRC Costa Rica</option>
          <option  value="CUP">CUP Cuba</option>
          <option  value="CVE">CVE Cape Verde</option>
          <option  value="CYP">CYP Cyprus</option>
          <option  value="CZK">CZK Czech Republic</option>
          <option  value="DEM">DEM Germany (-> Euro)</option>
          <option  value="DJF">DJF Djibouti</option>
          <option  value="DKK">DKK Denmark</option>
          <option  value="DOP">DOP Dominican Republic</option>
          <option  value="DZD">DZD Algeria</option>
          <option  value="ECS">ECS Ecuador</option>
          <option  value="EEK">EEK Estonia</option>
          <option  value="EGP">EGP Egypt</option>
          <option  value="ERN">ERN Eritrea</option>
          <option  value="ESP">ESP Spain (-> Euro)</option>
          <option  value="ETB">ETB Ethiopia</option>
          <option  value="EUR">EUR Euroland</option>
          <option  value="FIM">FIM Finland (-> Euro)</option>
          <option  value="FJD">FJD Fiji</option>
          <option  value="FKP">FKP Falkland Islands</option>
          <option  value="FRF">FRF France (-> Euro)</option>
          <option  value="GBP">GBP Great-Britain</option>
          <option  value="GEL">GEL Georgia</option>
          <option  value="GHC">GHC Ghana</option>
          <option  value="GIP">GIP Gibraltar</option>
          <option  value="GMD">GMD Gambia</option>
          <option  value="GNF">GNF Guinea</option>
          <option  value="GRD">GRD Greece (-> Euro)</option>
          <option  value="GTQ">GTQ Guatemala</option>
          <option  value="GYD">GYD Guyana</option>
          <option  value="HKD">HKD Hong-Kong</option>
          <option  value="HNL">HNL Honduras</option>
          <option  value="HRK">HRK Croatia</option>
          <option  value="HTG">HTG Haiti</option>
          <option  value="HUF">HUF Hungary</option>
          <option  value="IDR">IDR Indonesia</option>
          <option  value="IEP">IEP Ireland (-> Euro)</option>
          <option  value="ILS">ILS Israel</option>
          <option  value="IMP">IMP Isle of Man</option>
          <option  value="INR">INR India</option>
          <option  value="IQD">IQD Iraq</option>
          <option  value="IRR">IRR Iran</option>
          <option  value="ISK">ISK Iceland</option>
          <option  value="ITL">ITL Italy (-> Euro)</option>
          <option  value="JEP">JEP Jersey</option>
          <option  value="JMD">JMD Jamaica</option>
          <option value="JOD">JOD Jordania</option>
          <option  value="JPY">JPY Japan</option>
          <option  value="KES">KES Kenya</option>
          <option  value="KGS">KGS Kyrgyzstan</option>
          <option  value="KHR">KHR Cambodia</option>
          <option  value="KMF">KMF Comoros</option>
          <option  value="KPW">KPW North Korea</option>
          <option  value="KRW">KRW South Korea</option>
          <option  value="KWD">KWD Kuwait</option>
          <option  value="KYD">KYD Cayman Islands</option>
          <option  value="KZT">KZT Kazakhstan</option>
          <option  value="LAK">LAK Laos</option>
          <option  value="LBP">LBP Lebanon</option>
          <option  value="LKR">LKR Sri Lanka</option>
          <option  value="LRD">LRD Liberia</option>
          <option  value="LSL">LSL Lesotho</option>
          <option  value="LTL">LTL Lithuania</option>
          <option  value="LUF">LUF Luxembourg (-> Euro)</option>
          <option  value="LVL">LVL Latvia</option>
          <option  value="LYD">LYD Libya</option>
          <option  value="MAD">MAD Morocco</option>
          <option  value="MDL">MDL Moldova</option>
          <option  value="MGF">MGF Madagascar</option>
          <option  value="MKD">MKD Macedonia</option>
          <option  value="MMK">MMK Myanmar</option>
          <option  value="MNT">MNT Mongolia</option>
          <option  value="MOP">MOP Macau</option>
          <option  value="MRO">MRO Mauritania</option>
          <option  value="MTL">MTL Malta</option>
          <option  value="MUR">MUR Mauritius Island</option>
          <option  value="MVR">MVR Maldives</option>
          <option  value="MWK">MWK Malawi</option>
          <option  value="MXN">MXN Mexico</option>
          <option  value="MYR">MYR Malaysia</option>
          <option  value="MZM">MZM Mozambique</option>
          <option  value="NAD">NAD Namibia</option>
          <option  value="NGN">NGN Nigeria</option>
          <option  value="NIO">NIO Nicaragua</option>
          <option  value="NLG">NLG Holland (-> Euro)</option>
          <option  value="NOK">NOK Norway</option>
          <option  value="NPR">NPR Nepal</option>
          <option  value="NTD">NTD Taiwan</option>
          <option  value="NZD">NZD New-Zealand</option>
          <option  value="OMR">OMR Oman</option>
          <option  value="PAB">PAB Panama</option>
          <option  value="PEN">PEN Peru</option>
          <option  value="PGK">PGK Papua New Guinea</option>
          <option  value="PHP">PHP Philippines</option>
          <option  value="PKR">PKR Pakistan</option>
          <option  value="PLN">PLN Poland</option>
          <option  value="PSL">PSL Seborga</option>
          <option  value="PTE">PTE Portugal (-> Euro)</option>
          <option  value="PYG">PYG Paraguay</option>
          <option  value="QAR">QAR Qatar</option>
          <option  value="ROL">ROL Romania</option>
          <option  value="RUB">RUB Russia</option>
          <option  value="RWF">RWF Rwanda</option>
          <option  value="SAR">SAR Saudi Arabia</option>
          <option  value="SBD">SBD Solomon Islands</option>
          <option  value="SCR">SCR Seychelles</option>
          <option  value="SDD">SDD Sudan (Dinar)</option>
          <option  value="SDP">SDP Sudan (Pound)</option>
          <option  value="SEK">SEK Sweden</option>
          <option  value="SGD">SGD Singapore</option>
          <option  value="SHP">SHP Saint Helena</option>
          <option  value="SIT">SIT Slovenia</option>
          <option  value="SKK">SKK Slovakia</option>
          <option  value="SLL">SLL Sierra Leone</option>
          <option  value="SOS">SOS Somalia</option>
          <option  value="SRG">SRG Suriname</option>
          <option  value="STD">STD Saint Tome/Principe</option>
          <option  value="SVC">SVC El Salvador</option>
          <option  value="SYP">SYP Syria</option>
          <option  value="SZL">SZL Swaziland</option>
          <option  value="THB">THB Thailand</option>
          <option  value="TJS">TJS Tajikistan</option>
          <option  value="TMM">TMM Turkmenistan</option>
          <option  value="TND">TND Tunisia</option>
          <option  value="TOP">TOP Tonga</option>
          <option  value="TRL">TRL Turkey (-2004)</option>
          <option  value="TRY">TRY Turkey (2005-)</option>
          <option  value="TTD">TTD Trinidad & Tobago</option>
          <option  value="TVD">TVD Tuvalu</option>
          <option  value="TWD">TWD Taiwan (NTD)</option>
          <option  value="TZS">TZS Tanzania</option>
          <option  value="UAH">UAH Ukraine</option>
          <option  value="UGX">UGX Uganda</option>
          <option  value="USD">USD United States</option>
          <option  value="UYP">UYP Uruguay</option>
          <option  value="UZS">UZS Uzbekistan</option>
          <option  value="VEB">VEB Venezuela</option>
          <option  value="VND">VND Vietnam</option>
          <option  value="VUV">VUV Vanuatu</option>
          <option  value="WST">WST Samoa (Western)</option>
          <option  value="XAF">XAF CFA Franc BEAC</option>
          <option  value="XAG">XAG Silver gram</option>
          <option  value="XAU">XAU Gold gram</option>
          <option  value="XCD">XCD East Caribbean</option>
          <option  value="XDR">XDR Special Drawing Right</option>
          <option  value="XEU">XEU ECU-European Curr. Unit</option>
          <option  value="XOF">XOF CFA Franc BCEAO</option>
          <option  value="XPD">XPD Palladium gram</option>
          <option  value="XPF">XPF French Pacific</option>
          <option  value="XPT">XPT Platinium gram</option>
          <option  value="YER">YER Yemen</option>
          <option  value="YUN">YUN Yugoslavia</option>
          <option  value="ZAR">ZAR South Africa</option>
          <option  value="ZMK">ZMK Zambia</option>
          <option  value="ZWD">ZWD Zimbabwe</option>
        </select>
      </span></td>
    </tr>
    <tr>
      <td class="data style3 style4">Ge&ccedil;ici G&ouml;rev Hangi &Uuml;nvan olarak yap&#305;lacak </td>
      <td bgcolor="#FFFFE6"><label><span class="comment style2 style1">
        <?
		echo "<select name=\"unvan\">";
        echo "<option value=\"\"></option> ";
        include 'includes/unvancon.php';
         echo "</select> ";

?>
      </span></label></td>
      <td valign="middle" bgcolor="80B0D8" class="comment style2 style1">&nbsp;</td>
      <td class="data style1 style3"><div align="right" class="style4">Vize Harcamalar&#305; </div></td>
      <td bgcolor="#FFFFCC"><input name="vize" type="text" id="vize"></td>
      <td valign="middle" bgcolor="#FFFFCC" class="comment style2 style1"><span class="comment style2">
        <select name=vizec id="vizec" >
          <option  value="---" selected>Se&ccedil;iniz</option>
          <option  value="ADF" >ADF Andorra (Franc)</option>
          <option  value="ADP">ADP Andorra (Peseta)</option>
          <option  value="AED">AED United Arabic Emir.</option>
          <option  value="AFA">AFA Afghanistan</option>
          <option  value="ALL">ALL Albania</option>
          <option  value="AMD">AMD Armenia</option>
          <option  value="ANG">ANG NL Antilla</option>
          <option  value="AON">AON Angola</option>
          <option  value="ARS">ARS Argentina</option>
          <option  value="ATS">ATS Austria (-> Euro)</option>
          <option  value="AUD">AUD Australia</option>
          <option  value="AWG">AWG Aruba</option>
          <option  value="AZM">AZM Azerbaijan</option>
          <option  value="BBD">BBD Barbados</option>
          <option  value="BDT">BDT Bangladesh</option>
          <option  value="BEF">BEF Belgium (-> Euro)</option>
          <option  value="BGL">BGL Bulgaria</option>
          <option  value="BHD">BHD Bahrain</option>
          <option  value="BIF">BIF Burundi</option>
          <option  value="BMD">BMD Bermuda</option>
          <option  value="BND">BND Brunei</option>
          <option  value="BOB">BOB Bolivia</option>
          <option  value="BRL">BRL Brasil</option>
          <option  value="BSD">BSD Bahamas</option>
          <option  value="BTN">BTN Bhutan</option>
          <option  value="BWP">BWP Botswana</option>
          <option  value="BYR">BYR Belarus</option>
          <option  value="BZD">BZD Belize</option>
          <option  value="CAD">CAD Canada</option>
          <option  value="CDF">CDF Congo/Kinshasa</option>
          <option  value="CHF">CHF Switzerland</option>
          <option  value="CLP">CLP Chile</option>
          <option  value="CNY">CNY China</option>
          <option  value="COP">COP Colombia</option>
          <option  value="CRC">CRC Costa Rica</option>
          <option  value="CUP">CUP Cuba</option>
          <option  value="CVE">CVE Cape Verde</option>
          <option  value="CYP">CYP Cyprus</option>
          <option  value="CZK">CZK Czech Republic</option>
          <option  value="DEM">DEM Germany (-> Euro)</option>
          <option  value="DJF">DJF Djibouti</option>
          <option  value="DKK">DKK Denmark</option>
          <option  value="DOP">DOP Dominican Republic</option>
          <option  value="DZD">DZD Algeria</option>
          <option  value="ECS">ECS Ecuador</option>
          <option  value="EEK">EEK Estonia</option>
          <option  value="EGP">EGP Egypt</option>
          <option  value="ERN">ERN Eritrea</option>
          <option  value="ESP">ESP Spain (-> Euro)</option>
          <option  value="ETB">ETB Ethiopia</option>
          <option  value="EUR">EUR Euroland</option>
          <option  value="FIM">FIM Finland (-> Euro)</option>
          <option  value="FJD">FJD Fiji</option>
          <option  value="FKP">FKP Falkland Islands</option>
          <option  value="FRF">FRF France (-> Euro)</option>
          <option  value="GBP">GBP Great-Britain</option>
          <option  value="GEL">GEL Georgia</option>
          <option  value="GHC">GHC Ghana</option>
          <option  value="GIP">GIP Gibraltar</option>
          <option  value="GMD">GMD Gambia</option>
          <option  value="GNF">GNF Guinea</option>
          <option  value="GRD">GRD Greece (-> Euro)</option>
          <option  value="GTQ">GTQ Guatemala</option>
          <option  value="GYD">GYD Guyana</option>
          <option  value="HKD">HKD Hong-Kong</option>
          <option  value="HNL">HNL Honduras</option>
          <option  value="HRK">HRK Croatia</option>
          <option  value="HTG">HTG Haiti</option>
          <option  value="HUF">HUF Hungary</option>
          <option  value="IDR">IDR Indonesia</option>
          <option  value="IEP">IEP Ireland (-> Euro)</option>
          <option  value="ILS">ILS Israel</option>
          <option  value="IMP">IMP Isle of Man</option>
          <option  value="INR">INR India</option>
          <option  value="IQD">IQD Iraq</option>
          <option  value="IRR">IRR Iran</option>
          <option  value="ISK">ISK Iceland</option>
          <option  value="ITL">ITL Italy (-> Euro)</option>
          <option  value="JEP">JEP Jersey</option>
          <option  value="JMD">JMD Jamaica</option>
          <option value="JOD">JOD Jordania</option>
          <option  value="JPY">JPY Japan</option>
          <option  value="KES">KES Kenya</option>
          <option  value="KGS">KGS Kyrgyzstan</option>
          <option  value="KHR">KHR Cambodia</option>
          <option  value="KMF">KMF Comoros</option>
          <option  value="KPW">KPW North Korea</option>
          <option  value="KRW">KRW South Korea</option>
          <option  value="KWD">KWD Kuwait</option>
          <option  value="KYD">KYD Cayman Islands</option>
          <option  value="KZT">KZT Kazakhstan</option>
          <option  value="LAK">LAK Laos</option>
          <option  value="LBP">LBP Lebanon</option>
          <option  value="LKR">LKR Sri Lanka</option>
          <option  value="LRD">LRD Liberia</option>
          <option  value="LSL">LSL Lesotho</option>
          <option  value="LTL">LTL Lithuania</option>
          <option  value="LUF">LUF Luxembourg (-> Euro)</option>
          <option  value="LVL">LVL Latvia</option>
          <option  value="LYD">LYD Libya</option>
          <option  value="MAD">MAD Morocco</option>
          <option  value="MDL">MDL Moldova</option>
          <option  value="MGF">MGF Madagascar</option>
          <option  value="MKD">MKD Macedonia</option>
          <option  value="MMK">MMK Myanmar</option>
          <option  value="MNT">MNT Mongolia</option>
          <option  value="MOP">MOP Macau</option>
          <option  value="MRO">MRO Mauritania</option>
          <option  value="MTL">MTL Malta</option>
          <option  value="MUR">MUR Mauritius Island</option>
          <option  value="MVR">MVR Maldives</option>
          <option  value="MWK">MWK Malawi</option>
          <option  value="MXN">MXN Mexico</option>
          <option  value="MYR">MYR Malaysia</option>
          <option  value="MZM">MZM Mozambique</option>
          <option  value="NAD">NAD Namibia</option>
          <option  value="NGN">NGN Nigeria</option>
          <option  value="NIO">NIO Nicaragua</option>
          <option  value="NLG">NLG Holland (-> Euro)</option>
          <option  value="NOK">NOK Norway</option>
          <option  value="NPR">NPR Nepal</option>
          <option  value="NTD">NTD Taiwan</option>
          <option  value="NZD">NZD New-Zealand</option>
          <option  value="OMR">OMR Oman</option>
          <option  value="PAB">PAB Panama</option>
          <option  value="PEN">PEN Peru</option>
          <option  value="PGK">PGK Papua New Guinea</option>
          <option  value="PHP">PHP Philippines</option>
          <option  value="PKR">PKR Pakistan</option>
          <option  value="PLN">PLN Poland</option>
          <option  value="PSL">PSL Seborga</option>
          <option  value="PTE">PTE Portugal (-> Euro)</option>
          <option  value="PYG">PYG Paraguay</option>
          <option  value="QAR">QAR Qatar</option>
          <option  value="ROL">ROL Romania</option>
          <option  value="RUB">RUB Russia</option>
          <option  value="RWF">RWF Rwanda</option>
          <option  value="SAR">SAR Saudi Arabia</option>
          <option  value="SBD">SBD Solomon Islands</option>
          <option  value="SCR">SCR Seychelles</option>
          <option  value="SDD">SDD Sudan (Dinar)</option>
          <option  value="SDP">SDP Sudan (Pound)</option>
          <option  value="SEK">SEK Sweden</option>
          <option  value="SGD">SGD Singapore</option>
          <option  value="SHP">SHP Saint Helena</option>
          <option  value="SIT">SIT Slovenia</option>
          <option  value="SKK">SKK Slovakia</option>
          <option  value="SLL">SLL Sierra Leone</option>
          <option  value="SOS">SOS Somalia</option>
          <option  value="SRG">SRG Suriname</option>
          <option  value="STD">STD Saint Tome/Principe</option>
          <option  value="SVC">SVC El Salvador</option>
          <option  value="SYP">SYP Syria</option>
          <option  value="SZL">SZL Swaziland</option>
          <option  value="THB">THB Thailand</option>
          <option  value="TJS">TJS Tajikistan</option>
          <option  value="TMM">TMM Turkmenistan</option>
          <option  value="TND">TND Tunisia</option>
          <option  value="TOP">TOP Tonga</option>
          <option  value="TRL">TRL Turkey (-2004)</option>
          <option  value="TRY">TRY Turkey (2005-)</option>
          <option  value="TTD">TTD Trinidad & Tobago</option>
          <option  value="TVD">TVD Tuvalu</option>
          <option  value="TWD">TWD Taiwan (NTD)</option>
          <option  value="TZS">TZS Tanzania</option>
          <option  value="UAH">UAH Ukraine</option>
          <option  value="UGX">UGX Uganda</option>
          <option  value="USD">USD United States</option>
          <option  value="UYP">UYP Uruguay</option>
          <option  value="UZS">UZS Uzbekistan</option>
          <option  value="VEB">VEB Venezuela</option>
          <option  value="VND">VND Vietnam</option>
          <option  value="VUV">VUV Vanuatu</option>
          <option  value="WST">WST Samoa (Western)</option>
          <option  value="XAF">XAF CFA Franc BEAC</option>
          <option  value="XAG">XAG Silver gram</option>
          <option  value="XAU">XAU Gold gram</option>
          <option  value="XCD">XCD East Caribbean</option>
          <option  value="XDR">XDR Special Drawing Right</option>
          <option  value="XEU">XEU ECU-European Curr. Unit</option>
          <option  value="XOF">XOF CFA Franc BCEAO</option>
          <option  value="XPD">XPD Palladium gram</option>
          <option  value="XPF">XPF French Pacific</option>
          <option  value="XPT">XPT Platinium gram</option>
          <option  value="YER">YER Yemen</option>
          <option  value="YUN">YUN Yugoslavia</option>
          <option  value="ZAR">ZAR South Africa</option>
          <option  value="ZMK">ZMK Zambia</option>
          <option  value="ZWD">ZWD Zimbabwe</option>
        </select>
      </span></td>
    </tr>
    <tr>
      <td class="data style3 style4">Ge&ccedil;ici G&ouml;rev Ba&#351;lang&#305;&ccedil; Tarihi </td>
      <td bgcolor="#FFFFE6"><div id="basic_container"></div>
          <input name="bastarih" type="text" id="popup_container" /></td>
      <td valign="middle" bgcolor="80B0D8" class="comment style2 style1">&nbsp;</td>
      <td class="data style1 style3"><div align="right" class="style4">Sa&#287;l&#305;k Sigortas&#305; </div></td>
      <td bgcolor="#FFFFCC"><input name="saglik" type="text" id="saglik"></td>
      <td valign="middle" bgcolor="#FFFFCC" class="comment style2 style1"><span class="comment style2">
        <select name=saglikc id="saglikc" >
          <option  value="---" selected>Se&ccedil;iniz</option>
          <option  value="ADF" >ADF Andorra (Franc)</option>
          <option  value="ADP">ADP Andorra (Peseta)</option>
          <option  value="AED">AED United Arabic Emir.</option>
          <option  value="AFA">AFA Afghanistan</option>
          <option  value="ALL">ALL Albania</option>
          <option  value="AMD">AMD Armenia</option>
          <option  value="ANG">ANG NL Antilla</option>
          <option  value="AON">AON Angola</option>
          <option  value="ARS">ARS Argentina</option>
          <option  value="ATS">ATS Austria (-> Euro)</option>
          <option  value="AUD">AUD Australia</option>
          <option  value="AWG">AWG Aruba</option>
          <option  value="AZM">AZM Azerbaijan</option>
          <option  value="BBD">BBD Barbados</option>
          <option  value="BDT">BDT Bangladesh</option>
          <option  value="BEF">BEF Belgium (-> Euro)</option>
          <option  value="BGL">BGL Bulgaria</option>
          <option  value="BHD">BHD Bahrain</option>
          <option  value="BIF">BIF Burundi</option>
          <option  value="BMD">BMD Bermuda</option>
          <option  value="BND">BND Brunei</option>
          <option  value="BOB">BOB Bolivia</option>
          <option  value="BRL">BRL Brasil</option>
          <option  value="BSD">BSD Bahamas</option>
          <option  value="BTN">BTN Bhutan</option>
          <option  value="BWP">BWP Botswana</option>
          <option  value="BYR">BYR Belarus</option>
          <option  value="BZD">BZD Belize</option>
          <option  value="CAD">CAD Canada</option>
          <option  value="CDF">CDF Congo/Kinshasa</option>
          <option  value="CHF">CHF Switzerland</option>
          <option  value="CLP">CLP Chile</option>
          <option  value="CNY">CNY China</option>
          <option  value="COP">COP Colombia</option>
          <option  value="CRC">CRC Costa Rica</option>
          <option  value="CUP">CUP Cuba</option>
          <option  value="CVE">CVE Cape Verde</option>
          <option  value="CYP">CYP Cyprus</option>
          <option  value="CZK">CZK Czech Republic</option>
          <option  value="DEM">DEM Germany (-> Euro)</option>
          <option  value="DJF">DJF Djibouti</option>
          <option  value="DKK">DKK Denmark</option>
          <option  value="DOP">DOP Dominican Republic</option>
          <option  value="DZD">DZD Algeria</option>
          <option  value="ECS">ECS Ecuador</option>
          <option  value="EEK">EEK Estonia</option>
          <option  value="EGP">EGP Egypt</option>
          <option  value="ERN">ERN Eritrea</option>
          <option  value="ESP">ESP Spain (-> Euro)</option>
          <option  value="ETB">ETB Ethiopia</option>
          <option  value="EUR">EUR Euroland</option>
          <option  value="FIM">FIM Finland (-> Euro)</option>
          <option  value="FJD">FJD Fiji</option>
          <option  value="FKP">FKP Falkland Islands</option>
          <option  value="FRF">FRF France (-> Euro)</option>
          <option  value="GBP">GBP Great-Britain</option>
          <option  value="GEL">GEL Georgia</option>
          <option  value="GHC">GHC Ghana</option>
          <option  value="GIP">GIP Gibraltar</option>
          <option  value="GMD">GMD Gambia</option>
          <option  value="GNF">GNF Guinea</option>
          <option  value="GRD">GRD Greece (-> Euro)</option>
          <option  value="GTQ">GTQ Guatemala</option>
          <option  value="GYD">GYD Guyana</option>
          <option  value="HKD">HKD Hong-Kong</option>
          <option  value="HNL">HNL Honduras</option>
          <option  value="HRK">HRK Croatia</option>
          <option  value="HTG">HTG Haiti</option>
          <option  value="HUF">HUF Hungary</option>
          <option  value="IDR">IDR Indonesia</option>
          <option  value="IEP">IEP Ireland (-> Euro)</option>
          <option  value="ILS">ILS Israel</option>
          <option  value="IMP">IMP Isle of Man</option>
          <option  value="INR">INR India</option>
          <option  value="IQD">IQD Iraq</option>
          <option  value="IRR">IRR Iran</option>
          <option  value="ISK">ISK Iceland</option>
          <option  value="ITL">ITL Italy (-> Euro)</option>
          <option  value="JEP">JEP Jersey</option>
          <option  value="JMD">JMD Jamaica</option>
          <option value="JOD">JOD Jordania</option>
          <option  value="JPY">JPY Japan</option>
          <option  value="KES">KES Kenya</option>
          <option  value="KGS">KGS Kyrgyzstan</option>
          <option  value="KHR">KHR Cambodia</option>
          <option  value="KMF">KMF Comoros</option>
          <option  value="KPW">KPW North Korea</option>
          <option  value="KRW">KRW South Korea</option>
          <option  value="KWD">KWD Kuwait</option>
          <option  value="KYD">KYD Cayman Islands</option>
          <option  value="KZT">KZT Kazakhstan</option>
          <option  value="LAK">LAK Laos</option>
          <option  value="LBP">LBP Lebanon</option>
          <option  value="LKR">LKR Sri Lanka</option>
          <option  value="LRD">LRD Liberia</option>
          <option  value="LSL">LSL Lesotho</option>
          <option  value="LTL">LTL Lithuania</option>
          <option  value="LUF">LUF Luxembourg (-> Euro)</option>
          <option  value="LVL">LVL Latvia</option>
          <option  value="LYD">LYD Libya</option>
          <option  value="MAD">MAD Morocco</option>
          <option  value="MDL">MDL Moldova</option>
          <option  value="MGF">MGF Madagascar</option>
          <option  value="MKD">MKD Macedonia</option>
          <option  value="MMK">MMK Myanmar</option>
          <option  value="MNT">MNT Mongolia</option>
          <option  value="MOP">MOP Macau</option>
          <option  value="MRO">MRO Mauritania</option>
          <option  value="MTL">MTL Malta</option>
          <option  value="MUR">MUR Mauritius Island</option>
          <option  value="MVR">MVR Maldives</option>
          <option  value="MWK">MWK Malawi</option>
          <option  value="MXN">MXN Mexico</option>
          <option  value="MYR">MYR Malaysia</option>
          <option  value="MZM">MZM Mozambique</option>
          <option  value="NAD">NAD Namibia</option>
          <option  value="NGN">NGN Nigeria</option>
          <option  value="NIO">NIO Nicaragua</option>
          <option  value="NLG">NLG Holland (-> Euro)</option>
          <option  value="NOK">NOK Norway</option>
          <option  value="NPR">NPR Nepal</option>
          <option  value="NTD">NTD Taiwan</option>
          <option  value="NZD">NZD New-Zealand</option>
          <option  value="OMR">OMR Oman</option>
          <option  value="PAB">PAB Panama</option>
          <option  value="PEN">PEN Peru</option>
          <option  value="PGK">PGK Papua New Guinea</option>
          <option  value="PHP">PHP Philippines</option>
          <option  value="PKR">PKR Pakistan</option>
          <option  value="PLN">PLN Poland</option>
          <option  value="PSL">PSL Seborga</option>
          <option  value="PTE">PTE Portugal (-> Euro)</option>
          <option  value="PYG">PYG Paraguay</option>
          <option  value="QAR">QAR Qatar</option>
          <option  value="ROL">ROL Romania</option>
          <option  value="RUB">RUB Russia</option>
          <option  value="RWF">RWF Rwanda</option>
          <option  value="SAR">SAR Saudi Arabia</option>
          <option  value="SBD">SBD Solomon Islands</option>
          <option  value="SCR">SCR Seychelles</option>
          <option  value="SDD">SDD Sudan (Dinar)</option>
          <option  value="SDP">SDP Sudan (Pound)</option>
          <option  value="SEK">SEK Sweden</option>
          <option  value="SGD">SGD Singapore</option>
          <option  value="SHP">SHP Saint Helena</option>
          <option  value="SIT">SIT Slovenia</option>
          <option  value="SKK">SKK Slovakia</option>
          <option  value="SLL">SLL Sierra Leone</option>
          <option  value="SOS">SOS Somalia</option>
          <option  value="SRG">SRG Suriname</option>
          <option  value="STD">STD Saint Tome/Principe</option>
          <option  value="SVC">SVC El Salvador</option>
          <option  value="SYP">SYP Syria</option>
          <option  value="SZL">SZL Swaziland</option>
          <option  value="THB">THB Thailand</option>
          <option  value="TJS">TJS Tajikistan</option>
          <option  value="TMM">TMM Turkmenistan</option>
          <option  value="TND">TND Tunisia</option>
          <option  value="TOP">TOP Tonga</option>
          <option  value="TRL">TRL Turkey (-2004)</option>
          <option  value="TRY">TRY Turkey (2005-)</option>
          <option  value="TTD">TTD Trinidad & Tobago</option>
          <option  value="TVD">TVD Tuvalu</option>
          <option  value="TWD">TWD Taiwan (NTD)</option>
          <option  value="TZS">TZS Tanzania</option>
          <option  value="UAH">UAH Ukraine</option>
          <option  value="UGX">UGX Uganda</option>
          <option  value="USD">USD United States</option>
          <option  value="UYP">UYP Uruguay</option>
          <option  value="UZS">UZS Uzbekistan</option>
          <option  value="VEB">VEB Venezuela</option>
          <option  value="VND">VND Vietnam</option>
          <option  value="VUV">VUV Vanuatu</option>
          <option  value="WST">WST Samoa (Western)</option>
          <option  value="XAF">XAF CFA Franc BEAC</option>
          <option  value="XAG">XAG Silver gram</option>
          <option  value="XAU">XAU Gold gram</option>
          <option  value="XCD">XCD East Caribbean</option>
          <option  value="XDR">XDR Special Drawing Right</option>
          <option  value="XEU">XEU ECU-European Curr. Unit</option>
          <option  value="XOF">XOF CFA Franc BCEAO</option>
          <option  value="XPD">XPD Palladium gram</option>
          <option  value="XPF">XPF French Pacific</option>
          <option  value="XPT">XPT Platinium gram</option>
          <option  value="YER">YER Yemen</option>
          <option  value="YUN">YUN Yugoslavia</option>
          <option  value="ZAR">ZAR South Africa</option>
          <option  value="ZMK">ZMK Zambia</option>
          <option  value="ZWD">ZWD Zimbabwe</option>
        </select>
      </span></td>
    </tr>
    <tr>
      <td class="data style3 style4">Ge&ccedil;ici G&ouml;rev Biti&#351; Tarihi </td>
      <td bgcolor="#FFFFE6"><div id="basic_container"></div>
          <input name="bittarih" type="text" id="popup_container2" /></td>
      <td valign="middle" bgcolor="80B0D8" class="comment style2 style1">&nbsp;</td>
      <td class="data style1 style3"><div align="right" class="style4">Yurtd&#305;&#351;&#305; &Ccedil;&#305;k&#305;&#351; Pul/Harc&#305; </div></td>
      <td bgcolor="#FFFFCC"><input name="harc" type="text" id="harc"></td>
      <td valign="middle" bgcolor="#FFFFCC" class="comment style2 style1"><span class="comment style2">
        <select name=harcc id="harcc" >
          <option  value="---" selected>Se&ccedil;iniz</option>
          <option  value="ADF" >ADF Andorra (Franc)</option>
          <option  value="ADP">ADP Andorra (Peseta)</option>
          <option  value="AED">AED United Arabic Emir.</option>
          <option  value="AFA">AFA Afghanistan</option>
          <option  value="ALL">ALL Albania</option>
          <option  value="AMD">AMD Armenia</option>
          <option  value="ANG">ANG NL Antilla</option>
          <option  value="AON">AON Angola</option>
          <option  value="ARS">ARS Argentina</option>
          <option  value="ATS">ATS Austria (-> Euro)</option>
          <option  value="AUD">AUD Australia</option>
          <option  value="AWG">AWG Aruba</option>
          <option  value="AZM">AZM Azerbaijan</option>
          <option  value="BBD">BBD Barbados</option>
          <option  value="BDT">BDT Bangladesh</option>
          <option  value="BEF">BEF Belgium (-> Euro)</option>
          <option  value="BGL">BGL Bulgaria</option>
          <option  value="BHD">BHD Bahrain</option>
          <option  value="BIF">BIF Burundi</option>
          <option  value="BMD">BMD Bermuda</option>
          <option  value="BND">BND Brunei</option>
          <option  value="BOB">BOB Bolivia</option>
          <option  value="BRL">BRL Brasil</option>
          <option  value="BSD">BSD Bahamas</option>
          <option  value="BTN">BTN Bhutan</option>
          <option  value="BWP">BWP Botswana</option>
          <option  value="BYR">BYR Belarus</option>
          <option  value="BZD">BZD Belize</option>
          <option  value="CAD">CAD Canada</option>
          <option  value="CDF">CDF Congo/Kinshasa</option>
          <option  value="CHF">CHF Switzerland</option>
          <option  value="CLP">CLP Chile</option>
          <option  value="CNY">CNY China</option>
          <option  value="COP">COP Colombia</option>
          <option  value="CRC">CRC Costa Rica</option>
          <option  value="CUP">CUP Cuba</option>
          <option  value="CVE">CVE Cape Verde</option>
          <option  value="CYP">CYP Cyprus</option>
          <option  value="CZK">CZK Czech Republic</option>
          <option  value="DEM">DEM Germany (-> Euro)</option>
          <option  value="DJF">DJF Djibouti</option>
          <option  value="DKK">DKK Denmark</option>
          <option  value="DOP">DOP Dominican Republic</option>
          <option  value="DZD">DZD Algeria</option>
          <option  value="ECS">ECS Ecuador</option>
          <option  value="EEK">EEK Estonia</option>
          <option  value="EGP">EGP Egypt</option>
          <option  value="ERN">ERN Eritrea</option>
          <option  value="ESP">ESP Spain (-> Euro)</option>
          <option  value="ETB">ETB Ethiopia</option>
          <option  value="EUR">EUR Euroland</option>
          <option  value="FIM">FIM Finland (-> Euro)</option>
          <option  value="FJD">FJD Fiji</option>
          <option  value="FKP">FKP Falkland Islands</option>
          <option  value="FRF">FRF France (-> Euro)</option>
          <option  value="GBP">GBP Great-Britain</option>
          <option  value="GEL">GEL Georgia</option>
          <option  value="GHC">GHC Ghana</option>
          <option  value="GIP">GIP Gibraltar</option>
          <option  value="GMD">GMD Gambia</option>
          <option  value="GNF">GNF Guinea</option>
          <option  value="GRD">GRD Greece (-> Euro)</option>
          <option  value="GTQ">GTQ Guatemala</option>
          <option  value="GYD">GYD Guyana</option>
          <option  value="HKD">HKD Hong-Kong</option>
          <option  value="HNL">HNL Honduras</option>
          <option  value="HRK">HRK Croatia</option>
          <option  value="HTG">HTG Haiti</option>
          <option  value="HUF">HUF Hungary</option>
          <option  value="IDR">IDR Indonesia</option>
          <option  value="IEP">IEP Ireland (-> Euro)</option>
          <option  value="ILS">ILS Israel</option>
          <option  value="IMP">IMP Isle of Man</option>
          <option  value="INR">INR India</option>
          <option  value="IQD">IQD Iraq</option>
          <option  value="IRR">IRR Iran</option>
          <option  value="ISK">ISK Iceland</option>
          <option  value="ITL">ITL Italy (-> Euro)</option>
          <option  value="JEP">JEP Jersey</option>
          <option  value="JMD">JMD Jamaica</option>
          <option value="JOD">JOD Jordania</option>
          <option  value="JPY">JPY Japan</option>
          <option  value="KES">KES Kenya</option>
          <option  value="KGS">KGS Kyrgyzstan</option>
          <option  value="KHR">KHR Cambodia</option>
          <option  value="KMF">KMF Comoros</option>
          <option  value="KPW">KPW North Korea</option>
          <option  value="KRW">KRW South Korea</option>
          <option  value="KWD">KWD Kuwait</option>
          <option  value="KYD">KYD Cayman Islands</option>
          <option  value="KZT">KZT Kazakhstan</option>
          <option  value="LAK">LAK Laos</option>
          <option  value="LBP">LBP Lebanon</option>
          <option  value="LKR">LKR Sri Lanka</option>
          <option  value="LRD">LRD Liberia</option>
          <option  value="LSL">LSL Lesotho</option>
          <option  value="LTL">LTL Lithuania</option>
          <option  value="LUF">LUF Luxembourg (-> Euro)</option>
          <option  value="LVL">LVL Latvia</option>
          <option  value="LYD">LYD Libya</option>
          <option  value="MAD">MAD Morocco</option>
          <option  value="MDL">MDL Moldova</option>
          <option  value="MGF">MGF Madagascar</option>
          <option  value="MKD">MKD Macedonia</option>
          <option  value="MMK">MMK Myanmar</option>
          <option  value="MNT">MNT Mongolia</option>
          <option  value="MOP">MOP Macau</option>
          <option  value="MRO">MRO Mauritania</option>
          <option  value="MTL">MTL Malta</option>
          <option  value="MUR">MUR Mauritius Island</option>
          <option  value="MVR">MVR Maldives</option>
          <option  value="MWK">MWK Malawi</option>
          <option  value="MXN">MXN Mexico</option>
          <option  value="MYR">MYR Malaysia</option>
          <option  value="MZM">MZM Mozambique</option>
          <option  value="NAD">NAD Namibia</option>
          <option  value="NGN">NGN Nigeria</option>
          <option  value="NIO">NIO Nicaragua</option>
          <option  value="NLG">NLG Holland (-> Euro)</option>
          <option  value="NOK">NOK Norway</option>
          <option  value="NPR">NPR Nepal</option>
          <option  value="NTD">NTD Taiwan</option>
          <option  value="NZD">NZD New-Zealand</option>
          <option  value="OMR">OMR Oman</option>
          <option  value="PAB">PAB Panama</option>
          <option  value="PEN">PEN Peru</option>
          <option  value="PGK">PGK Papua New Guinea</option>
          <option  value="PHP">PHP Philippines</option>
          <option  value="PKR">PKR Pakistan</option>
          <option  value="PLN">PLN Poland</option>
          <option  value="PSL">PSL Seborga</option>
          <option  value="PTE">PTE Portugal (-> Euro)</option>
          <option  value="PYG">PYG Paraguay</option>
          <option  value="QAR">QAR Qatar</option>
          <option  value="ROL">ROL Romania</option>
          <option  value="RUB">RUB Russia</option>
          <option  value="RWF">RWF Rwanda</option>
          <option  value="SAR">SAR Saudi Arabia</option>
          <option  value="SBD">SBD Solomon Islands</option>
          <option  value="SCR">SCR Seychelles</option>
          <option  value="SDD">SDD Sudan (Dinar)</option>
          <option  value="SDP">SDP Sudan (Pound)</option>
          <option  value="SEK">SEK Sweden</option>
          <option  value="SGD">SGD Singapore</option>
          <option  value="SHP">SHP Saint Helena</option>
          <option  value="SIT">SIT Slovenia</option>
          <option  value="SKK">SKK Slovakia</option>
          <option  value="SLL">SLL Sierra Leone</option>
          <option  value="SOS">SOS Somalia</option>
          <option  value="SRG">SRG Suriname</option>
          <option  value="STD">STD Saint Tome/Principe</option>
          <option  value="SVC">SVC El Salvador</option>
          <option  value="SYP">SYP Syria</option>
          <option  value="SZL">SZL Swaziland</option>
          <option  value="THB">THB Thailand</option>
          <option  value="TJS">TJS Tajikistan</option>
          <option  value="TMM">TMM Turkmenistan</option>
          <option  value="TND">TND Tunisia</option>
          <option  value="TOP">TOP Tonga</option>
          <option  value="TRL">TRL Turkey (-2004)</option>
          <option  value="TRY">TRY Turkey (2005-)</option>
          <option  value="TTD">TTD Trinidad & Tobago</option>
          <option  value="TVD">TVD Tuvalu</option>
          <option  value="TWD">TWD Taiwan (NTD)</option>
          <option  value="TZS">TZS Tanzania</option>
          <option  value="UAH">UAH Ukraine</option>
          <option  value="UGX">UGX Uganda</option>
          <option  value="USD">USD United States</option>
          <option  value="UYP">UYP Uruguay</option>
          <option  value="UZS">UZS Uzbekistan</option>
          <option  value="VEB">VEB Venezuela</option>
          <option  value="VND">VND Vietnam</option>
          <option  value="VUV">VUV Vanuatu</option>
          <option  value="WST">WST Samoa (Western)</option>
          <option  value="XAF">XAF CFA Franc BEAC</option>
          <option  value="XAG">XAG Silver gram</option>
          <option  value="XAU">XAU Gold gram</option>
          <option  value="XCD">XCD East Caribbean</option>
          <option  value="XDR">XDR Special Drawing Right</option>
          <option  value="XEU">XEU ECU-European Curr. Unit</option>
          <option  value="XOF">XOF CFA Franc BCEAO</option>
          <option  value="XPD">XPD Palladium gram</option>
          <option  value="XPF">XPF French Pacific</option>
          <option  value="XPT">XPT Platinium gram</option>
          <option  value="YER">YER Yemen</option>
          <option  value="YUN">YUN Yugoslavia</option>
          <option  value="ZAR">ZAR South Africa</option>
          <option  value="ZMK">ZMK Zambia</option>
          <option  value="ZWD">ZWD Zimbabwe</option>
        </select>
      </span></td>
    </tr>
    <tr>
      <td class="data style3 style4">&nbsp;</td>
      <td bgcolor="#FFFFE6">&nbsp;</td>
      <td valign="middle" bgcolor="80B0D8" class="comment style2 style1">&nbsp;</td>
      <td class="data style1 style3"><div align="right" class="style4">Bilet Tutar&#305; </div></td>
      <td bgcolor="#FFFFCC"><input name="bilet" type="text" id="bilet"></td>
      <td valign="middle" bgcolor="#FFFFCC" class="comment style2 style1"><span class="comment style2">
        <select name=biletc id="biletc" >
          <option  value="---" selected>Se&ccedil;iniz</option>
          <option  value="ADF" >ADF Andorra (Franc)</option>
          <option  value="ADP">ADP Andorra (Peseta)</option>
          <option  value="AED">AED United Arabic Emir.</option>
          <option  value="AFA">AFA Afghanistan</option>
          <option  value="ALL">ALL Albania</option>
          <option  value="AMD">AMD Armenia</option>
          <option  value="ANG">ANG NL Antilla</option>
          <option  value="AON">AON Angola</option>
          <option  value="ARS">ARS Argentina</option>
          <option  value="ATS">ATS Austria (-> Euro)</option>
          <option  value="AUD">AUD Australia</option>
          <option  value="AWG">AWG Aruba</option>
          <option  value="AZM">AZM Azerbaijan</option>
          <option  value="BBD">BBD Barbados</option>
          <option  value="BDT">BDT Bangladesh</option>
          <option  value="BEF">BEF Belgium (-> Euro)</option>
          <option  value="BGL">BGL Bulgaria</option>
          <option  value="BHD">BHD Bahrain</option>
          <option  value="BIF">BIF Burundi</option>
          <option  value="BMD">BMD Bermuda</option>
          <option  value="BND">BND Brunei</option>
          <option  value="BOB">BOB Bolivia</option>
          <option  value="BRL">BRL Brasil</option>
          <option  value="BSD">BSD Bahamas</option>
          <option  value="BTN">BTN Bhutan</option>
          <option  value="BWP">BWP Botswana</option>
          <option  value="BYR">BYR Belarus</option>
          <option  value="BZD">BZD Belize</option>
          <option  value="CAD">CAD Canada</option>
          <option  value="CDF">CDF Congo/Kinshasa</option>
          <option  value="CHF">CHF Switzerland</option>
          <option  value="CLP">CLP Chile</option>
          <option  value="CNY">CNY China</option>
          <option  value="COP">COP Colombia</option>
          <option  value="CRC">CRC Costa Rica</option>
          <option  value="CUP">CUP Cuba</option>
          <option  value="CVE">CVE Cape Verde</option>
          <option  value="CYP">CYP Cyprus</option>
          <option  value="CZK">CZK Czech Republic</option>
          <option  value="DEM">DEM Germany (-> Euro)</option>
          <option  value="DJF">DJF Djibouti</option>
          <option  value="DKK">DKK Denmark</option>
          <option  value="DOP">DOP Dominican Republic</option>
          <option  value="DZD">DZD Algeria</option>
          <option  value="ECS">ECS Ecuador</option>
          <option  value="EEK">EEK Estonia</option>
          <option  value="EGP">EGP Egypt</option>
          <option  value="ERN">ERN Eritrea</option>
          <option  value="ESP">ESP Spain (-> Euro)</option>
          <option  value="ETB">ETB Ethiopia</option>
          <option  value="EUR">EUR Euroland</option>
          <option  value="FIM">FIM Finland (-> Euro)</option>
          <option  value="FJD">FJD Fiji</option>
          <option  value="FKP">FKP Falkland Islands</option>
          <option  value="FRF">FRF France (-> Euro)</option>
          <option  value="GBP">GBP Great-Britain</option>
          <option  value="GEL">GEL Georgia</option>
          <option  value="GHC">GHC Ghana</option>
          <option  value="GIP">GIP Gibraltar</option>
          <option  value="GMD">GMD Gambia</option>
          <option  value="GNF">GNF Guinea</option>
          <option  value="GRD">GRD Greece (-> Euro)</option>
          <option  value="GTQ">GTQ Guatemala</option>
          <option  value="GYD">GYD Guyana</option>
          <option  value="HKD">HKD Hong-Kong</option>
          <option  value="HNL">HNL Honduras</option>
          <option  value="HRK">HRK Croatia</option>
          <option  value="HTG">HTG Haiti</option>
          <option  value="HUF">HUF Hungary</option>
          <option  value="IDR">IDR Indonesia</option>
          <option  value="IEP">IEP Ireland (-> Euro)</option>
          <option  value="ILS">ILS Israel</option>
          <option  value="IMP">IMP Isle of Man</option>
          <option  value="INR">INR India</option>
          <option  value="IQD">IQD Iraq</option>
          <option  value="IRR">IRR Iran</option>
          <option  value="ISK">ISK Iceland</option>
          <option  value="ITL">ITL Italy (-> Euro)</option>
          <option  value="JEP">JEP Jersey</option>
          <option  value="JMD">JMD Jamaica</option>
          <option value="JOD">JOD Jordania</option>
          <option  value="JPY">JPY Japan</option>
          <option  value="KES">KES Kenya</option>
          <option  value="KGS">KGS Kyrgyzstan</option>
          <option  value="KHR">KHR Cambodia</option>
          <option  value="KMF">KMF Comoros</option>
          <option  value="KPW">KPW North Korea</option>
          <option  value="KRW">KRW South Korea</option>
          <option  value="KWD">KWD Kuwait</option>
          <option  value="KYD">KYD Cayman Islands</option>
          <option  value="KZT">KZT Kazakhstan</option>
          <option  value="LAK">LAK Laos</option>
          <option  value="LBP">LBP Lebanon</option>
          <option  value="LKR">LKR Sri Lanka</option>
          <option  value="LRD">LRD Liberia</option>
          <option  value="LSL">LSL Lesotho</option>
          <option  value="LTL">LTL Lithuania</option>
          <option  value="LUF">LUF Luxembourg (-> Euro)</option>
          <option  value="LVL">LVL Latvia</option>
          <option  value="LYD">LYD Libya</option>
          <option  value="MAD">MAD Morocco</option>
          <option  value="MDL">MDL Moldova</option>
          <option  value="MGF">MGF Madagascar</option>
          <option  value="MKD">MKD Macedonia</option>
          <option  value="MMK">MMK Myanmar</option>
          <option  value="MNT">MNT Mongolia</option>
          <option  value="MOP">MOP Macau</option>
          <option  value="MRO">MRO Mauritania</option>
          <option  value="MTL">MTL Malta</option>
          <option  value="MUR">MUR Mauritius Island</option>
          <option  value="MVR">MVR Maldives</option>
          <option  value="MWK">MWK Malawi</option>
          <option  value="MXN">MXN Mexico</option>
          <option  value="MYR">MYR Malaysia</option>
          <option  value="MZM">MZM Mozambique</option>
          <option  value="NAD">NAD Namibia</option>
          <option  value="NGN">NGN Nigeria</option>
          <option  value="NIO">NIO Nicaragua</option>
          <option  value="NLG">NLG Holland (-> Euro)</option>
          <option  value="NOK">NOK Norway</option>
          <option  value="NPR">NPR Nepal</option>
          <option  value="NTD">NTD Taiwan</option>
          <option  value="NZD">NZD New-Zealand</option>
          <option  value="OMR">OMR Oman</option>
          <option  value="PAB">PAB Panama</option>
          <option  value="PEN">PEN Peru</option>
          <option  value="PGK">PGK Papua New Guinea</option>
          <option  value="PHP">PHP Philippines</option>
          <option  value="PKR">PKR Pakistan</option>
          <option  value="PLN">PLN Poland</option>
          <option  value="PSL">PSL Seborga</option>
          <option  value="PTE">PTE Portugal (-> Euro)</option>
          <option  value="PYG">PYG Paraguay</option>
          <option  value="QAR">QAR Qatar</option>
          <option  value="ROL">ROL Romania</option>
          <option  value="RUB">RUB Russia</option>
          <option  value="RWF">RWF Rwanda</option>
          <option  value="SAR">SAR Saudi Arabia</option>
          <option  value="SBD">SBD Solomon Islands</option>
          <option  value="SCR">SCR Seychelles</option>
          <option  value="SDD">SDD Sudan (Dinar)</option>
          <option  value="SDP">SDP Sudan (Pound)</option>
          <option  value="SEK">SEK Sweden</option>
          <option  value="SGD">SGD Singapore</option>
          <option  value="SHP">SHP Saint Helena</option>
          <option  value="SIT">SIT Slovenia</option>
          <option  value="SKK">SKK Slovakia</option>
          <option  value="SLL">SLL Sierra Leone</option>
          <option  value="SOS">SOS Somalia</option>
          <option  value="SRG">SRG Suriname</option>
          <option  value="STD">STD Saint Tome/Principe</option>
          <option  value="SVC">SVC El Salvador</option>
          <option  value="SYP">SYP Syria</option>
          <option  value="SZL">SZL Swaziland</option>
          <option  value="THB">THB Thailand</option>
          <option  value="TJS">TJS Tajikistan</option>
          <option  value="TMM">TMM Turkmenistan</option>
          <option  value="TND">TND Tunisia</option>
          <option  value="TOP">TOP Tonga</option>
          <option  value="TRL">TRL Turkey (-2004)</option>
          <option  value="TRY">TRY Turkey (2005-)</option>
          <option  value="TTD">TTD Trinidad & Tobago</option>
          <option  value="TVD">TVD Tuvalu</option>
          <option  value="TWD">TWD Taiwan (NTD)</option>
          <option  value="TZS">TZS Tanzania</option>
          <option  value="UAH">UAH Ukraine</option>
          <option  value="UGX">UGX Uganda</option>
          <option  value="USD">USD United States</option>
          <option  value="UYP">UYP Uruguay</option>
          <option  value="UZS">UZS Uzbekistan</option>
          <option  value="VEB">VEB Venezuela</option>
          <option  value="VND">VND Vietnam</option>
          <option  value="VUV">VUV Vanuatu</option>
          <option  value="WST">WST Samoa (Western)</option>
          <option  value="XAF">XAF CFA Franc BEAC</option>
          <option  value="XAG">XAG Silver gram</option>
          <option  value="XAU">XAU Gold gram</option>
          <option  value="XCD">XCD East Caribbean</option>
          <option  value="XDR">XDR Special Drawing Right</option>
          <option  value="XEU">XEU ECU-European Curr. Unit</option>
          <option  value="XOF">XOF CFA Franc BCEAO</option>
          <option  value="XPD">XPD Palladium gram</option>
          <option  value="XPF">XPF French Pacific</option>
          <option  value="XPT">XPT Platinium gram</option>
          <option  value="YER">YER Yemen</option>
          <option  value="YUN">YUN Yugoslavia</option>
          <option  value="ZAR">ZAR South Africa</option>
          <option  value="ZMK">ZMK Zambia</option>
          <option  value="ZWD">ZWD Zimbabwe</option>
        </select>
      </span></td>
    </tr>
    <tr>
      <td class="data style3 style4">&nbsp;</td>
      <td bgcolor="#FFFFE6"><span class="style2">
        <label>
        <input type="submit" name="Submit" value="Kaydet" />
        </label>
        <span class="comment">
        <input name="Submit2" type="reset" value="Temizle" />
      </span></span></td>
      <td valign="middle" bgcolor="80B0D8" class="comment">&nbsp;</td>
      <td valign="middle" class="comment"><div align="right"><span class="style4"></span></div></td>
      <td valign="middle" class="comment">&nbsp;</td>
      <td valign="middle" class="comment">&nbsp;</td>
    </tr>
  </table>
</form>
</body>
</html>
